### ISSUE TITLE
[DOCS] Build Failing for the latest merge pull request #40 

### ISSUE THREAD

**Issue by kokamkarsahil** [WasmEdge/docs#46]
### Description

The build is failing with latest commit it is caused due to the https://github.com/WasmEdge/docs/actions/runs/4839635400/jobs/8624785967#step:7:32

From what I can concluded it is caused because of the remove footer links which I mentioned https://github.com/WasmEdge/docs/pull/40#pullrequestreview-1405157286 was later replaced by the following code which caused the issue

https://github.com/WasmEdge/docs/blob/d84fbbd2865786b6ee974a0c1b02ac6cdea7bdd2/docusaurus.config.js#LL140C31-L143C31

It is acting as baseurl which results in broken link for other locales.

I will create a PR to fix this issue ASAP!

**Comment by Bhardwaj-Himanshu** [comment]
Hi @kokamkarsahil,
Here is a little help from my side to make your work easy.

The broken links are everywhere ranging from 404.html to `/docs/zh/embed/use-case/yomo`.
With a little research I found out this is happening due to breaking of `/docs/zh/docs` link, which has been used multiple times.

Tried finding the broken link using string search and got it, which could look like this-
![image](https://user-images.githubusercontent.com/74407676/235340047-d2ced764-bd46-4a63-9f2a-8e511037b384.png)

After changing the path from `/docs/zh/docs` to `/docs/zh` or `any other link`.
Saved my changes and tried running `npm run build` which still builds the file without changes.

Unable to solve this issue, the build still throws up errors.

Also I think the `/zh` version of documentation builds automatically as I can find `/docs/zh` anywhere else except the `build folder`

Let me know your thoughts on this and if I could be of any help.

Also tagging @adithyaakrishna , to drop some suggestions and help if you could!
Thanks
