### ISSUE TITLE
The latest CI fails

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/docs#78]
### Describe the bug.

The latest CI fails https://github.com/WasmEdge/docs/actions/runs/5066235102/jobs/9095783281

### Operating Environment

GitHub Action

**Comment by alabulei1** [comment]
@adithyaakrishna  Can you help take a look?

**Comment by kokamkarsahil** [comment]
@alabulei1  I already pointed out what's wrong 2 days ago 

> Sure, before fixing conflicts the main branch needs to fix https://github.com/WasmEdge/docs/actions/runs/5041542766/jobs/9041329340#step:7:19 else this branch will also break as a node dependency is causing the build to fail it.

https://github.com/WasmEdge/docs/pull/71#issuecomment-1556584602

I thought it will be fixed after pointing it out. I will create a PR to fix it ASAP.

**Comment by kokamkarsahil** [comment]
@alabulei1 I have created PR to fix it #79

**Comment by notfathomless** [comment]
There are three ways to fix this:
1. Put `@node-rs/jieba-linux-x64-gnu` as a first class dependency in `package.json`
--> This will fix the build on x64 linux with gnu libs, such as the github's ubuntu runner images, but attempting to run on any other environment will simply crash it because npm install `@node-rs/jieba-linux-x64-gnu` with check the package's target environment/platform required and fail to match on windows, linux and other permutations, as shown below.
![image](https://github.com/WasmEdge/docs/assets/57017288/cb6f26e3-31c9-4a14-b24d-754bf6c429ab)

2. Use `npm install` which installs from package.json and rebuild lock file instead of `npm ci` which only builds from lock file.
--> It will be frowned upon by many, and might cause more `but it works on my machine` errors later in future.

3. Renew the Lock File (`package-lock.json`) with the assumption that the current lock file is broken.
I will put my case why I feel that the lock file is broken.
[Listing](https://github.com/WasmEdge/docs/blob/e6ef484b855776822d77d2db21fc6fe3a14d7470/package-lock.json#L2895)
: Here you see that all the available binaries are listed.
![image](https://github.com/WasmEdge/docs/assets/57017288/3829a998-dadf-4f44-aaae-f6075e6d467b)
Just a few lines down you find instructions on which package to use and their maching target specs.
However we only find two listings here:
![image](https://github.com/WasmEdge/docs/assets/57017288/efc4f1da-7b7e-43e8-af38-a11ccc403544)
Where are the listings for other platforms too?
Because `package-lock.json` should be platform agonistic so it should have contained those too in my humble opinion, but I might be wrong.

Now I will reference the `package-lock.json` which my machine produces on both windows 11 x64 with node 16.0.0 & 16.14.2 (both lockfile v2 & v3) and ubuntu x64 node 18.x.x (lockfile v3 only)

![image](https://github.com/WasmEdge/docs/assets/57017288/2a16b1c1-2c4c-4b31-afc5-6488bb43639b)
As you can see it will provide a listing of all the maching cases and their package resolution, thereby making the lockfile truly platform agonistic.

And this package-lock.json remains same even if I run npm install in windows or linux.
I don't have a macos to test it, but I think it will show a similar behaviour.

So, in this case I find that simply updating the package-lock.json will be the right approach.

Thank you.
Saikat Dey.
